-- MySQL Script generated by MySQL Workbench
-- Mon Aug 24 11:34:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_escola` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca_escola` ;

-- -----------------------------------------------------
-- Table `biblioteca_escola`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`autor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nacionalidade` VARCHAR(100) NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`aluno` (
  `id` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`funcionario` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cargo_ou_turno` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`livro` (
  `isbn` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `ano_publicacao` DATE NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_livro_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `biblioteca_escola`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`emprestimo` (
  `id` INT NOT NULL,
  `data_emprestimo` DATE NULL,
  `data_devolucao_prevista` DATE NULL,
  `aluno_id` INT NOT NULL,
  `funcionario_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_emprestimo_funcionario1_idx` (`funcionario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `biblioteca_escola`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `biblioteca_escola`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`autor_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`autor_livro` (
  `autor_id` INT NOT NULL,
  `livro_isbn` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`autor_id`, `livro_isbn`),
  INDEX `fk_autor_has_livro_livro1_idx` (`livro_isbn` ASC) VISIBLE,
  INDEX `fk_autor_has_livro_autor1_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_autor_has_livro_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `biblioteca_escola`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_livro_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `biblioteca_escola`.`livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_escola`.`livro_emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_escola`.`livro_emprestimo` (
  `livro_isbn` VARCHAR(100) NOT NULL,
  `emprestimo_id` INT NOT NULL,
  PRIMARY KEY (`livro_isbn`, `emprestimo_id`),
  INDEX `fk_livro_has_emprestimo_emprestimo1_idx` (`emprestimo_id` ASC) VISIBLE,
  INDEX `fk_livro_has_emprestimo_livro1_idx` (`livro_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_emprestimo_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `biblioteca_escola`.`livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_emprestimo_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `biblioteca_escola`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
